baseURL = "https://www.sajuria.com"
title = "jsajuria"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
canonifyurls = true

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
author = "Javier Sajuria"
description = "Javier Sajuria's personal website"
keywords = "research, personal"
info = "Senior Lecturer (Associate Professor) in Politics @QMUL and occassional podcast host"
avatarURL = "images/javier_website.jpg"
#gravatar = "john.doe@example.com"
footerContent = ""
dateFormat = "January 2, 2006"

hideCredits = false
hideCopyright = false


# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"



  # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = ["css/css_style.css"]



[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 1
url = "https://github.com/jsajuria/"


[[params.social]]
name = "Twitter"
icon = "fa fa-twitter"
weight = 3
url = "https://twitter.com/jsajuria/"



[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"

[languages.es-cl]
languageName = ":chile:"
title = "Javier Sajuria"

[languages.es-cl.params]
author = "Javier Sajuria"
info = "Profesor Asociado de Ciencia Política @QMUL"
description = "Sitio personal de Javier Sajuria"
keywords = "investigación, personal"
#footerContent = "Coloque algum texto aqui."

[[languages.es-cl.menu.main]]
name = "Sobre"
weight = 1
url = "about/"

[[languages.es-cl.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.es-cl.menu.main]]
name = "Proyectos"
weight = 3
url = "projects/"

[[languages.es-cl.menu.main]]
name = "Contacto"
weight = 5
url = "contact/"
